target:
  url: http://loki:3100/loki/api/v1/push
limits_config:
  max_query_range: 672h # 28 days
  max_lookback_time: 30d # 28 days from today
  rate_limit: 1000 # 1000 requests per second

overrides:
  "example":
    max_query_range: 10h # 10 hours
    max_lookback_time: 1d # 1 day from today
    rate_limit: 100 # 100 requests per second